apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infraregistry-com
  namespace: ingress-external
spec:
  issuerRef:
    name: letsencrypt-infraregistry-com
    kind: ClusterIssuer
  secretName: infraregistry-com
  dnsNames:
  - infraregistry.com
  - "*.infraregistry.com"
  # - "*.dev.infraregistry.com"
