apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-infraregistry-com
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matthew@matthewdavis.io
    privateKeySecretRef:
      name: letsencrypt-infraregistry-com
    solvers:
      - dns01:
          cloudflare:
            email: matthew@matthewdavis.io
            apiTokenSecretRef:
              name: cloudflare-api-key-infraregistry
              key: api-key
