apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matthew@matthewdavis.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: matthew@matthewdavis.io
            apiTokenSecretRef:
              name: cloudflare-api-key-infraregistry
              key: api-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: matthew@matthewdavis.io
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: matthew@matthewdavis.io
            apiTokenSecretRef:
              name: cloudflare-api-key-infraregistry
              key: api-key
