# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
  namespace: infraregistry
  labels:
    app: spa
spec:
  selector:
    matchLabels:
      app: spa
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spa
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      imagePullSecrets:
        - name: ghcr
      restartPolicy: Always
      containers:
      - name: spa
        image: ghcr.io/infraregistry/spa:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
